const trial='#join';
const models=[['AI Affiliate Business','Create useful content around products and tools you genuinely believe in.'],['YouTube Business','Use AI to accelerate research, scripting, production and optimization.'],['Content + Search','Build useful content around problems people are already searching for.'],['Personal Brand','Turn your experience and interests into audience, services and offers.'],['Digital Products','Create resources, templates, education or systems that solve real problems.'],['Unclaimed Funds','The original Unclaimed CEO model remains a blueprint for the right entrepreneur.']];
const path=[['01','CHOOSE','Find a realistic model that fits your strengths, goals and available time.'],['02','BUILD','Use AI to accelerate your brand, website, content, research and systems.'],['03','LAUNCH','Stop endlessly preparing. Put something real into the market.'],['04','ATTRACT','Build attention through content, search, YouTube and social.'],['05','MONETIZE','Use legitimate revenue models that fit the business you are building.'],['06','SCALE','Improve what works. Simplify and automate repeatable work.']];
const inside=[['Build Paths','Know what to work on next.'],['AI Tool Stack','Tools we actually use, test and believe are worth considering.'],['Coaching','Get real guidance when you get stuck.'],['Build With Joe','Follow real experiments, wins, failures and lessons.'],['Community','Build beside people working toward similar goals.'],['Templates + Systems','Start from something useful instead of a blank page.']];
function CTA({children='START YOUR FREE 7 DAY TRIAL'}){return <a className="cta" href={trial}>{children}<span>→</span></a>}
export default function Home(){return <main>
<header><a className="logo" href="#top"><span className="mark">U</span><b>UNCLAIMED <i>CEO</i></b></a><nav><a href="#how">How It Works</a><a href="#community">Community</a><a href="#about">About</a><a href="#login">Login</a></nav><CTA>START FREE</CTA></header>
<section className="hero" id="top"><div className="glow g1"/><div className="glow g2"/><div className="heroCopy"><div className="eyebrow">AI POWERED BUSINESS BUILDING</div><h1>BUILD SOMETHING<br/><em>YOU OWN.</em></h1><p className="lead">Use AI to build an online income stream, create more freedom, and start making your 9 to 5 optional.</p><div className="beliefs"><span>✓ No programming required</span><span>✓ No huge following required</span><span>✓ Don't figure it out alone</span></div><CTA/><small>$0 today. 7 days free. Then $9/month as a Founding Member. Cancel anytime.</small></div><div className="ecosystem"><div className="orbit o1"></div><div className="orbit o2"></div><div className="core"><span>YOUR</span><strong>IDEA</strong></div><div className="node n1"><b>AI</b><small>LEVERAGE</small></div><div className="node n2"><b>CONTENT</b><small>ATTENTION</small></div><div className="node n3"><b>BUSINESS</b><small>VALUE</small></div><div className="node n4"><b>AUDIENCE</b><small>TRUST</small></div><div className="ownership">OWNERSHIP <span>↑</span></div></div></section>
<section className="problem"><div className="kicker">THE REAL PROBLEM</div><h2>YOUR 9 TO 5 ISN'T THE PROBLEM.<br/><em>DEPENDING ON IT IS.</em></h2><div className="split"><div className="paycheck"><span>ONE EMPLOYER</span><div>ONE<br/><b>PAYCHECK</b></div><small>One source controls too many options.</small></div><div className="story"><p>Most people don't hate working.</p><h3>They hate having <em>no alternative.</em></h3><p>For parents, time has a different value. We're not promising retirement next month. We're helping you begin building something you own alongside the life you already have.</p><CTA>START BUILDING FREE</CTA></div></div></section>
<section className="storySection" id="about"><div className="kicker">WHY UNCLAIMED CEO EVOLVED</div><h2>I ALMOST BUILT THE<br/><em>WRONG BUSINESS AGAIN.</em></h2><div className="quote"><div className="avatar">JG</div><div><p>“I spent years building businesses and teaching one specific model: unclaimed funds. It worked. But I realized one business model isn't right for everyone.”</p><p>“Then AI changed what one person could accomplish. I didn't want to build another giant course. I wanted a place where entrepreneurs could actually <b>build together.</b>”</p><small>JOE GREEN · FOUNDER, UNCLAIMED CEO</small></div></div><div className="evolution"><span>ONE BUSINESS MODEL</span><b>→</b><strong>FIND + BUILD <em>YOUR</em> BUSINESS MODEL</strong></div></section>
<section className="old"><div className="kicker">INFORMATION ISN'T THE ANSWER</div><h2>YOU DON'T NEED<br/><em>ANOTHER COURSE.</em></h2><div className="course"><div className="modules"><b>THE OLD WAY</b>{['Module 01','Module 02','Module 03','Module 04','Module 05','... 42 more'].map(x=><span key={x}>{x}<i>▶</i></span>)}</div><div className="arrow">→</div><div className="next"><b>WHAT YOU ACTUALLY NEED</b>{['Direction','Implementation','Accountability','Feedback','Community'].map(x=><span key={x}>✓ {x}</span>)}<strong>KNOW WHAT TO DO <em>NEXT.</em></strong></div></div></section>
<section className="mechanism" id="how"><div className="kicker">THE NEW VEHICLE</div><h2>THE NEW WAY TO <em>BUILD.</em></h2><div className="equation"><div><i>✦</i><b>AI</b><small>Do more with less.</small></div><strong>+</strong><div><i>◇</i><b>BUSINESS</b><small>Build a real economic engine.</small></div><strong>+</strong><div><i>◎</i><b>COMMUNITY</b><small>Don't figure it out alone.</small></div><strong>=</strong><div className="result"><i>↗</i><b>OWNERSHIP</b><small>Build something that's yours.</small></div></div><p>AI provides leverage. Business creates value. Community keeps you moving.</p></section>
<section className="models"><div className="kicker">CHOOSE YOUR VEHICLE</div><h2>THERE'S MORE THAN ONE WAY<br/>TO <em>BUILD ONLINE.</em></h2><p className="intro">You don't need to know which one is right for you yet. That's part of what we'll help you figure out.</p><div className="grid">{models.map((m,i)=><article key={m[0]}><span>0{i+1}</span><h3>{m[0]}</h3><p>{m[1]}</p><i>↗</i></article>)}</div></section>
<section className="buildPath"><div className="kicker">THE UNCLAIMED CEO BUILD PATH</div><h2>FROM IDEA TO <em>INCOME.</em></h2><p>Not another curriculum to finish. A path to move through.</p><div className="steps">{path.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="community" id="community"><div className="kicker">INSIDE THE COMMUNITY</div><h2>DON'T JUST LEARN IT.<br/><em>BUILD IT.</em></h2><div className="communityGrid">{inside.map((x,i)=><article key={x[0]}><i>{['↗','✦','◎','◉','⌁','□'][i]}</i><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div><small>Some tools discussed inside the community may use affiliate links. We only recommend tools we believe provide genuine value.</small></section>
<section className="anti"><div className="kicker">A DIFFERENT KIND OF BUSINESS COMMUNITY</div><h2>NO LAMBOS. NO MAGIC BUTTONS.<br/><em>NO BS.</em></h2><div className="antiGrid"><div><b>THIS IS NOT</b>{['Guaranteed income','Get rich quick','Push button passive income','AI doing everything for you','Fake income screenshots'].map(x=><p key={x}>× {x}</p>)}</div><div className="yes"><b>THIS IS</b>{['Build something real','Use AI to move faster','Learn how online businesses work','Get help when you’re stuck','Build an asset you own'].map(x=><p key={x}>✓ {x}</p>)}</div></div></section>
<section className="offer" id="join"><div className="offerCard"><div className="kicker">COME BUILD WITH US</div><h2>7 DAYS <em>FREE.</em></h2><p>Full access to the Unclaimed CEO community. Explore it. Start building. Decide whether we've earned your continued membership.</p><div className="price"><strong>$0</strong><span>TODAY</span><i>→</i><strong>$9</strong><span>/ MONTH AFTER TRIAL</span></div><CTA>START MY FREE 7 DAY TRIAL</CTA><small>Cancel anytime. No hidden language. No tricks.</small></div></section>
<section className="why"><div><div className="kicker">FOUNDING MEMBERS</div><h2>WHY ONLY <em>$9?</em></h2></div><div><p>We're building the next generation of Unclaimed CEO alongside our earliest members.</p><p>Founding members help shape what gets taught, what gets built, which tools we test, which business models we explore, and what support members actually need.</p><p><b>The community should become more valuable as it grows.</b></p></div></section>
<section className="founder"><div className="founderVisual"><div className="photoPlaceholder"><span>JOE GREEN</span><small>AUTHENTIC FOUNDER PHOTO</small></div></div><div><div className="kicker">WHY I'M BUILDING THIS</div><h2>WORK BECAUSE YOU <em>WANT TO.</em><br/>NOT BECAUSE YOU HAVE NO OPTION.</h2><p>I'm a husband, dad, veteran, and entrepreneur. I believe technology has changed what one person with an idea can build.</p><p>Unclaimed CEO exists to help people use that leverage to build something of their own, without the hype, fake promises, or trying to figure everything out alone.</p><p className="signature">Let's build something you own.</p><b>Joe Green</b></div></section>
<section className="final"><div className="glow g3"/><div className="kicker">YOUR NEXT MOVE</div><h2>CLAIM YOUR <em>FREEDOM.</em></h2><h3>BUILD SOMETHING YOU OWN.</h3><p>Your business isn't going to build itself.<br/>But you don't have to build it alone.</p><CTA>JOIN UNCLAIMED CEO FREE</CTA><small>$0 today. 7 days free. Then $9/month. Cancel anytime.</small></section>
<footer><a className="logo"><span className="mark">U</span><b>UNCLAIMED <i>CEO</i></b></a><p>AI is leverage. Ownership is the outcome.</p><small>© 2026 Unclaimed CEO. Results vary. No income is guaranteed.</small></footer>
</main>}